numeroDigitado = int(input('Digite um Número para ver sua taboada:'))
print('-+'*12)
print(f'{numeroDigitado} + 1 = {numeroDigitado + 1}')
print(f'{numeroDigitado} + 2 = {numeroDigitado + 2}')
print(f'{numeroDigitado} + 3 = {numeroDigitado + 3}')
print(f'{numeroDigitado} + 4 = {numeroDigitado + 4}')
print(f'{numeroDigitado} + 5 = {numeroDigitado + 5}')
print(f'{numeroDigitado} + 6 = {numeroDigitado + 6}')
print(f'{numeroDigitado} + 7 = {numeroDigitado + 7}')
print(f'{numeroDigitado} + 8 = {numeroDigitado + 8}')
print(f'{numeroDigitado} + 9 = {numeroDigitado + 9}')
print(f'{numeroDigitado} + 10 = {numeroDigitado + 10}')
